/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/": [M1, M2, M3, L1, L2, P1];
		"/new": [M1, M2, M3, H1, L1, L2, P2, D1];
		"/notes/$id": [M1, M2, M3, M4, H2, L1, L2, P3];
		"/notes/$id/comments": [M1, M2, M3, M4, H3, D2];
		"/callback/oauth2": [M1, H4];
		"/my": [M1, H5, L1, P4];
		"/$$match": [M1, H6];
	}> {}
}

type M1 = $.Middleware<"M1", typeof import("../src/routes/+middleware")>;
declare module "../src/routes/+middleware" {
  const Run: $.Namespace<M1>;
  namespace Run {
    type Context = $.ContextForFile<M1>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/" | "/new" | "/notes/$id" | "/notes/$id/comments" | "/callback/oauth2" | "/my" | "/$$match"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type M2 = $.Middleware<"M2", typeof import("../src/routes/_protected/+middleware")>;
declare module "../src/routes/_protected/+middleware" {
  const Run: $.Namespace<M2>;
  namespace Run {
    type Context = $.ContextForFile<M2>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/" | "/new" | "/notes/$id" | "/notes/$id/comments"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type M3 = $.Middleware<"M3", typeof import("../src/routes/_protected/_home/+middleware")>;
declare module "../src/routes/_protected/_home/+middleware" {
  const Run: $.Namespace<M3>;
  namespace Run {
    type Context = $.ContextForFile<M3>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/" | "/new" | "/notes/$id" | "/notes/$id/comments"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type M4 = $.Middleware<"M4", typeof import("../src/routes/_protected/_home/notes/$id/+middleware")>;
declare module "../src/routes/_protected/_home/notes/$id/+middleware" {
  const Run: $.Namespace<M4>;
  namespace Run {
    type Context = $.ContextForFile<M4>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/notes/$id" | "/notes/$id/comments"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H1 = $.Handler<"H1", typeof import("../src/routes/_protected/_home/new/+handler")>;
declare module "../src/routes/_protected/_home/new/+handler" {
  const Run: $.Namespace<H1>;
  namespace Run {
    type Context = $.ContextForFile<H1>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/new"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H2 = $.Handler<"H2", typeof import("../src/routes/_protected/_home/notes/$id/+handler")>;
declare module "../src/routes/_protected/_home/notes/$id/+handler" {
  const Run: $.Namespace<H2>;
  namespace Run {
    type Context = $.ContextForFile<H2>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/notes/$id"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H3 = $.Handler<"H3", typeof import("../src/routes/_protected/_home/notes/$id/comments/+handler")>;
declare module "../src/routes/_protected/_home/notes/$id/comments/+handler" {
  const Run: $.Namespace<H3>;
  namespace Run {
    type Context = $.ContextForFile<H3>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/notes/$id/comments"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H4 = $.Handler<"H4", typeof import("../src/routes/callback/oauth2/+handler")>;
declare module "../src/routes/callback/oauth2/+handler" {
  const Run: $.Namespace<H4>;
  namespace Run {
    type Context = $.ContextForFile<H4>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/callback/oauth2"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H5 = $.Handler<"H5", typeof import("../src/routes/my/+handler")>;
declare module "../src/routes/my/+handler" {
  const Run: $.Namespace<H5>;
  namespace Run {
    type Context = $.ContextForFile<H5>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/my"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H6 = $.Handler<"H6", typeof import("../src/routes/$$match/+handler")>;
declare module "../src/routes/$$match/+handler" {
  const Run: $.Namespace<H6>;
  namespace Run {
    type Context = $.ContextForFile<H6>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/$$match"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type L1 = $.Template<"L1", typeof import("../src/routes/+layout.marko")>;
declare module "../src/routes/+layout.marko" {
  interface Input extends $.LayoutInput<L1> {}
  const Run: $.Namespace<L1>;
  namespace Run {
    type Context = $.ContextForFile<L1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/" | "/new" | "/notes/$id" | "/my"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type L2 = $.Template<"L2", typeof import("../src/routes/_protected/_home/+layout.marko")>;
declare module "../src/routes/_protected/_home/+layout.marko" {
  interface Input extends $.LayoutInput<L2> {}
  const Run: $.Namespace<L2>;
  namespace Run {
    type Context = $.ContextForFile<L2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/" | "/new" | "/notes/$id"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/_protected/_home/+page.marko")>;
declare module "../src/routes/_protected/_home/+page.marko" {
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P2 = $.Template<"P2", typeof import("../src/routes/_protected/_home/new/+page.marko")>;
declare module "../src/routes/_protected/_home/new/+page.marko" {
  const Run: $.Namespace<P2>;
  namespace Run {
    type Context = $.ContextForFile<P2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/new"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P3 = $.Template<"P3", typeof import("../src/routes/_protected/_home/notes/$id/+page.marko")>;
declare module "../src/routes/_protected/_home/notes/$id/+page.marko" {
  const Run: $.Namespace<P3>;
  namespace Run {
    type Context = $.ContextForFile<P3> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/notes/$id"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P4 = $.Template<"P4", typeof import("../src/routes/my/+page.marko")>;
declare module "../src/routes/my/+page.marko" {
  const Run: $.Namespace<P4>;
  namespace Run {
    type Context = $.ContextForFile<P4> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/my"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type D1 = $.Meta<"D1", typeof import("../src/routes/_protected/_home/new/+meta.json")>;

type D2 = $.Meta<"D2", typeof import("../src/routes/_protected/_home/notes/$id/comments/+meta")>;

declare module "../src/routes/+404.marko" {
  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = globalThis.MarkoRun.Route;
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

declare module "../src/routes/+500.marko" {
  export interface Input {
    error: unknown;
  }
  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = globalThis.MarkoRun.Route;
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}
