/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/foo/$fooId/bar/$barId": [P1];
	}> {}
}

type P1 = $.Template<"P1", typeof import("../src/routes/foo/$fooId/bar/$barId/+page.marko")>;
declare module "../src/routes/foo/$fooId/bar/$barId/+page.marko" {
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/foo/$fooId/bar/$barId"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}
