/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import "@marko/run/namespace";
import type Run from "@marko/run";


type Route1 = Run.Route<["fooId", "bar Id", "1bazId", "qux-Id"], undefined, `/foo/:fooId/bar/:bar Id/baz/:1bazId/:qux-Id`>;

declare module "@marko/run" {
	interface AppData {
		routes: Route1;
		get: "/foo/${fooId}/bar/${bar Id}/baz/${1bazId}/${qux-Id}";
		post: never;
	}
}

declare module "./foo/$fooId/bar/$bar Id/baz/$1bazId/$qux-Id/+page.marko" {
  export interface Input {
    renderBody: Marko.Body;
  }
  namespace MarkoRun {
    export * from "@marko/run/namespace";
    export type Route = Route1;
    export type Context = Run.Context<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export const route: Run.HandlerTypeFn<Handler>;
  }
}
