/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as Run from "@marko/run";


declare module "@marko/run" {
	interface AppData extends Run.DefineApp<{
		routes: {
			"/": { verb: "get"; };
			"/foo": { verb: "get" | "post"; };
			"/$id": { verb: "get"; };
			"/$$rest": { verb: "get"; };
			"/a/c": { verb: "get" | "post"; };
			"/a/d": { verb: "get" | "post"; };
			"/b/c": { verb: "get" | "post"; };
			"/b/d": { verb: "get" | "post"; };
		}
	}> {}
}

declare module "../src/routes/foo,(a,b).(c,d)+handler.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/foo" | "/a/c" | "/a/d" | "/b/c" | "/b/d"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/$id,a.d+middleware.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/$id" | "/a/d"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}

declare module "../src/routes/foo,$id,$$rest,+page.marko" {
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = Run.Routes["/" | "/foo" | "/$id" | "/$$rest"];
    export type Context = Run.MultiRouteContext<Route> & Marko.Global;
    export type Handler = Run.HandlerLike<Route>;
    export type GET = Run.HandlerLike<Route, "GET">;
    export type HEAD = Run.HandlerLike<Route, "HEAD">;
    export type POST = Run.HandlerLike<Route, "POST">;
    export type PUT = Run.HandlerLike<Route, "PUT">;
    export type DELETE = Run.HandlerLike<Route, "DELETE">;
    export type PATCH = Run.HandlerLike<Route, "PATCH">;
    export type OPTIONS = Run.HandlerLike<Route, "OPTIONS">;
    /** @deprecated use `((context, next) => { ... }) satisfies MarkoRun.Handler` instead */
    export const route: Run.HandlerTypeFn<Route>;
  }
}
