import baseAdapter, { type Adapter } from "@marko/run/adapter";
import fs from "fs/promises";
import path from "path";

export type { DockerPlatformInfo } from "./types";

/** The port the container listens on. Matches the server's default. */
const PORT = 3000;

export interface Options {
  /**
   * The base Docker image to build from. Defaults to `"node:20-alpine"`.
   */
  baseImage?: string;
}

export default function dockerAdapter(options: Options = {}): Adapter {
  const { baseImage = "node:20-alpine" } = options;
  const base = baseAdapter();

  return {
    ...base,
    name: "docker-adapter",

    viteConfig(config) {
      if (config.build?.ssr) {
        return {
          ssr: {
            // Bundle everything so the built server is self-contained and the
            // image doesn't need a `node_modules` install.
            noExternal: true,
          },
        };
      }
    },

    async buildEnd({ config }) {
      // During the client build `outDir` points at the static assets dir
      // (`<outDir>/public`); its parent is the build dir containing the
      // server entry (`index.mjs`).
      const publicDir = path.resolve(config.root, config.build.outDir);
      const distDir = path.dirname(publicDir);
      const relDist = path.relative(config.root, distDir) || ".";

      await writeIfAbsent(
        path.join(config.root, "Dockerfile"),
        dockerfile(baseImage, relDist),
      );
      await writeIfAbsent(
        path.join(config.root, ".dockerignore"),
        dockerignore(relDist),
      );
    },

    typeInfo(writer) {
      writer(
        `import type { DockerPlatformInfo } from '@marko/run-adapter-docker';`,
      );
      return "DockerPlatformInfo";
    },
  };
}

function dockerfile(baseImage: string, relDist: string) {
  return `# syntax=docker/dockerfile:1
# Generated by @marko/run-adapter-docker. Build your app before building this
# image (\`marko-run build\`), then \`docker build\`. Delete this file to have it
# regenerated, or edit it freely — it will not be overwritten once it exists.
FROM ${baseImage}

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=${PORT}

COPY ${relDist} ./${relDist}

EXPOSE ${PORT}
CMD ["node", "${path.posix.join(relDist, "index.mjs")}"]
`;
}

function dockerignore(relDist: string) {
  return `*
!${relDist}
`;
}

async function writeIfAbsent(file: string, contents: string) {
  try {
    await fs.access(file);
    // Already exists — leave the user's file untouched.
  } catch {
    await fs.writeFile(file, contents);
  }
}
