/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/aaa/$aId": [M1, H1, L1, P1];
		"/aaa/$aId/bbb/$bId": [M1, H1, L1, P1];
		"/aaa/$aId/bbb/$bId/ccc/$cId": [M1, H1, L1, P1];
		"/aaa/$aId/ccc/$cId": [M1, H1, L1, P1];
	}> {}
}

type M1 = $.Middleware<"M1", typeof import("../src/routes/+middleware")>;
declare module "../src/routes/+middleware" {
  const Run: $.Namespace<M1>;
  namespace Run {
    type Context = $.ContextForFile<M1>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/aaa/$aId" | "/aaa/$aId/bbb/$bId" | "/aaa/$aId/bbb/$bId/ccc/$cId" | "/aaa/$aId/ccc/$cId"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H1 = $.Handler<"H1", typeof import("../src/routes/aaa.$aId.(,bbb.$bId).(,ccc.$cId)/+handler")>;
declare module "../src/routes/aaa.$aId.(,bbb.$bId).(,ccc.$cId)/+handler" {
  const Run: $.Namespace<H1>;
  namespace Run {
    type Context = $.ContextForFile<H1>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/aaa/$aId" | "/aaa/$aId/bbb/$bId" | "/aaa/$aId/bbb/$bId/ccc/$cId" | "/aaa/$aId/ccc/$cId"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type L1 = $.Template<"L1", typeof import("../src/routes/+layout.marko")>;
declare module "../src/routes/+layout.marko" {
  interface Input extends $.LayoutInput<L1> {}
  const Run: $.Namespace<L1>;
  namespace Run {
    type Context = $.ContextForFile<L1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/aaa/$aId" | "/aaa/$aId/bbb/$bId" | "/aaa/$aId/bbb/$bId/ccc/$cId" | "/aaa/$aId/ccc/$cId"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/aaa.$aId.(,bbb.$bId).(,ccc.$cId)/+page.marko")>;
declare module "../src/routes/aaa.$aId.(,bbb.$bId).(,ccc.$cId)/+page.marko" {
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/aaa/$aId" | "/aaa/$aId/bbb/$bId" | "/aaa/$aId/bbb/$bId/ccc/$cId" | "/aaa/$aId/ccc/$cId"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}
