/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.

  AGENTS: before writing or changing route files, READ the cheat sheet shipped with @marko/run
  — require.resolve("@marko/run/cheatsheet.md"), typically node_modules/@marko/run/cheatsheet.md — for the
  routing, handler, middleware, and validation conventions this file's types describe.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/docs/$slug": [L1, P1, T1, T2, T3];
	}> {}
}

type L1 = $.Template<"L1", typeof import("../src/routes/+layout.marko")>;
declare module "../src/routes/+layout.marko" {
  interface Input extends $.LayoutInput<L1> {}
  const Run: $.Namespace<L1>;
  namespace Run {
    type Context = $.ContextForFile<L1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/docs/$slug/+page.marko")>;
declare module "../src/routes/docs/$slug/+page.marko" {
  interface Input extends $.PageInput<P1> {}
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T1 = $.PartialTemplate<"T1", "header", typeof import("../src/routes/@header.marko")>;
declare module "../src/routes/@header.marko" {
  const Run: $.Namespace<T1>;
  namespace Run {
    type Context = $.ContextForFile<T1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T2 = $.PartialTemplate<"T2", "header", typeof import("../src/routes/docs/@header.marko")>;
declare module "../src/routes/docs/@header.marko" {
  interface Input extends $.PartialInput<T2> {}
  const Run: $.Namespace<T2>;
  namespace Run {
    type Context = $.ContextForFile<T2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T3 = $.PartialTemplate<"T3", "header", typeof import("../src/routes/docs/$slug/@header.marko")>;
declare module "../src/routes/docs/$slug/@header.marko" {
  interface Input extends $.PartialInput<T3> {}
  const Run: $.Namespace<T3>;
  namespace Run {
    type Context = $.ContextForFile<T3> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}
