/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/foo/bar": [H1, D1];
		"/foo/baz": [H2, P1, D2];
	}> {}
}

type H1 = $.Handler<"H1", typeof import("../src/routes/foo/bar/+handler")>;
declare module "../src/routes/foo/bar/+handler" {
  const Run: $.Namespace<H1>;
  namespace Run {
    type Context = $.ContextForFile<H1>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/foo/bar"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type H2 = $.Handler<"H2", typeof import("../src/routes/foo/baz/+handler")>;
declare module "../src/routes/foo/baz/+handler" {
  const Run: $.Namespace<H2>;
  namespace Run {
    type Context = $.ContextForFile<H2>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/foo/baz"];
    export type Context = $.MultiRouteContext<Route>;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/foo/baz/+page.marko")>;
declare module "../src/routes/foo/baz/+page.marko" {
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/foo/baz"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type D1 = $.Meta<"D1", typeof import("../src/routes/foo/bar/+meta")>;
type D2 = $.Meta<"D2", typeof import("../src/routes/foo/baz/+meta.json")>;
