/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.

  AGENTS: before writing or changing route files, READ the cheat sheet shipped with @marko/run
  — require.resolve("@marko/run/cheatsheet.md"), typically node_modules/@marko/run/cheatsheet.md — for the
  routing, handler, middleware, and validation conventions this file's types describe.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/": [L1, P1, T1, T2];
		"/a": [L1, P2, T1, T2, T3];
		"/b": [L1, P3, T1, T2, T3];
		"/flat/page": [L1, P4, T1, T4, T2];
		"/docs": [L1, L2, P5, T1, T5, T2];
		"/docs/$slug": [L1, L2, P6, T1, T5, T6, T2, T7];
		"/blog": [H1, L1, P7, T1, T2, T8];
	}> {}
}

type H1 = $.Handler<"H1", typeof import("../src/routes/blog/+handler")>;
declare module "../src/routes/blog/+handler" {
  const Run: $.Namespace<H1>;
  namespace Run {
    type Context = $.ContextForFile<H1>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/blog"];
    /** @deprecated use `Run.Context` instead */
    export type Context = $.MultiRouteContext<Route>;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type L1 = $.Template<"L1", typeof import("../src/routes/+layout.marko")>;
declare module "../src/routes/+layout.marko" {
  interface Input extends $.LayoutInput<L1> {}
  const Run: $.Namespace<L1>;
  namespace Run {
    type Context = $.ContextForFile<L1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/" | "/a" | "/b" | "/flat/page" | "/docs" | "/docs/$slug" | "/blog"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type L2 = $.Template<"L2", typeof import("../src/routes/docs/+layout.marko")>;
declare module "../src/routes/docs/+layout.marko" {
  interface Input extends $.LayoutInput<L2> {}
  const Run: $.Namespace<L2>;
  namespace Run {
    type Context = $.ContextForFile<L2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs" | "/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/+page.marko")>;
declare module "../src/routes/+page.marko" {
  interface Input extends $.PageInput<P1> {}
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P2 = $.Template<"P2", typeof import("../src/routes/a+page.marko")>;
declare module "../src/routes/a+page.marko" {
  interface Input extends $.PageInput<P2> {}
  const Run: $.Namespace<P2>;
  namespace Run {
    type Context = $.ContextForFile<P2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/a"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P3 = $.Template<"P3", typeof import("../src/routes/b+page.marko")>;
declare module "../src/routes/b+page.marko" {
  interface Input extends $.PageInput<P3> {}
  const Run: $.Namespace<P3>;
  namespace Run {
    type Context = $.ContextForFile<P3> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/b"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P4 = $.Template<"P4", typeof import("../src/routes/flat.page+page.marko")>;
declare module "../src/routes/flat.page+page.marko" {
  interface Input extends $.PageInput<P4> {}
  const Run: $.Namespace<P4>;
  namespace Run {
    type Context = $.ContextForFile<P4> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/flat/page"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P5 = $.Template<"P5", typeof import("../src/routes/docs/+page.marko")>;
declare module "../src/routes/docs/+page.marko" {
  interface Input extends $.PageInput<P5> {}
  const Run: $.Namespace<P5>;
  namespace Run {
    type Context = $.ContextForFile<P5> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P6 = $.Template<"P6", typeof import("../src/routes/docs/$slug/+page.marko")>;
declare module "../src/routes/docs/$slug/+page.marko" {
  interface Input extends $.PageInput<P6> {}
  const Run: $.Namespace<P6>;
  namespace Run {
    type Context = $.ContextForFile<P6> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P7 = $.Template<"P7", typeof import("../src/routes/blog/+page.marko")>;
declare module "../src/routes/blog/+page.marko" {
  interface Input extends $.PageInput<P7> {}
  const Run: $.Namespace<P7>;
  namespace Run {
    type Context = $.ContextForFile<P7> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/blog"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type S1 = $.Template<"S1", typeof import("../src/routes/+404.marko")>;
declare module "../src/routes/+404.marko" {
  export interface Input extends $.PageInput<S1, [T1, T2]> {}
  const Run: $.Namespace<any>;
  namespace Run {
    type Context = $.ContextForFile<any> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = globalThis.MarkoRun.Route;
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type S2 = $.Template<"S2", typeof import("../src/routes/+500.marko")>;
declare module "../src/routes/+500.marko" {
  export interface Input extends $.PageInput<S2, [T1, T2]> {
    error: unknown;
  }
  const Run: $.Namespace<any>;
  namespace Run {
    type Context = $.ContextForFile<any> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = globalThis.MarkoRun.Route;
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T1 = $.PartialTemplate<"T1", "header", typeof import("../src/routes/@header.marko")>;
declare module "../src/routes/@header.marko" {
  const Run: $.Namespace<T1>;
  namespace Run {
    type Context = $.ContextForFile<T1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/" | "/a" | "/b" | "/flat/page" | "/docs" | "/docs/$slug" | "/blog"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T2 = $.PartialTemplate<"T2", "footer", typeof import("../src/routes/@footer.marko")>;
declare module "../src/routes/@footer.marko" {
  const Run: $.Namespace<T2>;
  namespace Run {
    type Context = $.ContextForFile<T2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/" | "/a" | "/b" | "/flat/page" | "/docs" | "/docs/$slug" | "/blog"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T3 = $.PartialTemplate<"T3", "nav", typeof import("../src/routes/(a,b)@nav.marko")>;
declare module "../src/routes/(a,b)@nav.marko" {
  const Run: $.Namespace<T3>;
  namespace Run {
    type Context = $.ContextForFile<T3> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/a" | "/b"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T4 = $.PartialTemplate<"T4", "header", typeof import("../src/routes/flat.page@header.marko")>;
declare module "../src/routes/flat.page@header.marko" {
  interface Input extends $.PartialInput<T4> {}
  const Run: $.Namespace<T4>;
  namespace Run {
    type Context = $.ContextForFile<T4> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/flat/page"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T5 = $.PartialTemplate<"T5", "header", typeof import("../src/routes/docs/@header.marko")>;
declare module "../src/routes/docs/@header.marko" {
  interface Input extends $.PartialInput<T5> {}
  const Run: $.Namespace<T5>;
  namespace Run {
    type Context = $.ContextForFile<T5> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs" | "/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T6 = $.PartialTemplate<"T6", "header", typeof import("../src/routes/docs/$slug/@header.marko")>;
declare module "../src/routes/docs/$slug/@header.marko" {
  interface Input extends $.PartialInput<T6> {}
  const Run: $.Namespace<T6>;
  namespace Run {
    type Context = $.ContextForFile<T6> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T7 = $.PartialTemplate<"T7", "sidebar", typeof import("../src/routes/docs/$slug/@sidebar.marko")>;
declare module "../src/routes/docs/$slug/@sidebar.marko" {
  const Run: $.Namespace<T7>;
  namespace Run {
    type Context = $.ContextForFile<T7> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/docs/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type T8 = $.PartialTemplate<"T8", "sidebar", typeof import("../src/routes/blog/@sidebar.marko")>;
declare module "../src/routes/blog/@sidebar.marko" {
  const Run: $.Namespace<T8>;
  namespace Run {
    type Context = $.ContextForFile<T8> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/blog"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}
