/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.

  AGENTS: before writing or changing route files, READ the cheat sheet shipped with @marko/run
  — require.resolve("@marko/run/cheatsheet.md"), typically node_modules/@marko/run/cheatsheet.md — for the
  routing, handler, middleware, and validation conventions this file's types describe.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/": [L1, P1];
		"/api": [H1];
		"/blog": [L1, L2, P2];
		"/blog/$slug": [L1, L2, P3];
		"/blog/tag/$$": [L1, L2, P4];
		"/about": [L1, P5];
		"/admin/users": [H2, L1, L3, P6];
	}> {}
}

type H1 = $.Handler<"H1", typeof import("../src/routes/api/+handler")>;
declare module "../src/routes/api/+handler" {
  const Run: $.Namespace<H1>;
  namespace Run {
    type Context = $.ContextForFile<H1>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/api"];
    /** @deprecated use `Run.Context` instead */
    export type Context = $.MultiRouteContext<Route>;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type H2 = $.Handler<"H2", typeof import("../src/routes/admin/users/+handler")>;
declare module "../src/routes/admin/users/+handler" {
  const Run: $.Namespace<H2>;
  namespace Run {
    type Context = $.ContextForFile<H2>;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/admin/users"];
    /** @deprecated use `Run.Context` instead */
    export type Context = $.MultiRouteContext<Route>;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type L1 = $.Template<"L1", typeof import("../src/routes/+layout.marko")>;
declare module "../src/routes/+layout.marko" {
  interface Input extends $.LayoutInput<L1> {}
  const Run: $.Namespace<L1>;
  namespace Run {
    type Context = $.ContextForFile<L1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/" | "/blog" | "/blog/$slug" | "/blog/tag/$$" | "/about" | "/admin/users"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type L2 = $.Template<"L2", typeof import("../src/routes/blog/+layout.marko")>;
declare module "../src/routes/blog/+layout.marko" {
  interface Input extends $.LayoutInput<L2> {}
  const Run: $.Namespace<L2>;
  namespace Run {
    type Context = $.ContextForFile<L2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/blog" | "/blog/$slug" | "/blog/tag/$$"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type L3 = $.Template<"L3", typeof import("../src/routes/admin/+layout.marko")>;
declare module "../src/routes/admin/+layout.marko" {
  interface Input extends $.LayoutInput<L3> {}
  const Run: $.Namespace<L3>;
  namespace Run {
    type Context = $.ContextForFile<L3> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/admin/users"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/+page.marko")>;
declare module "../src/routes/+page.marko" {
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P2 = $.Template<"P2", typeof import("../src/routes/blog/+page.marko")>;
declare module "../src/routes/blog/+page.marko" {
  const Run: $.Namespace<P2>;
  namespace Run {
    type Context = $.ContextForFile<P2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/blog"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P3 = $.Template<"P3", typeof import("../src/routes/blog/$slug/+page.marko")>;
declare module "../src/routes/blog/$slug/+page.marko" {
  const Run: $.Namespace<P3>;
  namespace Run {
    type Context = $.ContextForFile<P3> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/blog/$slug"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P4 = $.Template<"P4", typeof import("../src/routes/blog/tag.$$/+page.marko")>;
declare module "../src/routes/blog/tag.$$/+page.marko" {
  const Run: $.Namespace<P4>;
  namespace Run {
    type Context = $.ContextForFile<P4> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/blog/tag/$$"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P5 = $.Template<"P5", typeof import("../src/routes/about/+page.marko")>;
declare module "../src/routes/about/+page.marko" {
  const Run: $.Namespace<P5>;
  namespace Run {
    type Context = $.ContextForFile<P5> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/about"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P6 = $.Template<"P6", typeof import("../src/routes/admin/users/+page.marko")>;
declare module "../src/routes/admin/users/+page.marko" {
  const Run: $.Namespace<P6>;
  namespace Run {
    type Context = $.ContextForFile<P6> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/admin/users"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

declare module "../src/routes/+404.marko" {
  const Run: $.Namespace<any>;
  namespace Run {
    type Context = $.ContextForFile<any> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = globalThis.MarkoRun.Route;
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

declare module "../src/routes/+500.marko" {
  export interface Input {
    error: unknown;
  }
  const Run: $.Namespace<any>;
  namespace Run {
    type Context = $.ContextForFile<any> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = globalThis.MarkoRun.Route;
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}
