/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/": [L1, P1];
		"/item/new": [L1, P2];
		"/item/$id": [L1, P3];
		"/docs/intro": [L1, P4];
		"/docs/$$rest": [L1, P5];
	}> {}
}

type L1 = $.Template<"L1", typeof import("../src/routes/+layout.marko")>;
declare module "../src/routes/+layout.marko" {
  interface Input extends $.LayoutInput<L1> {}
  const Run: $.Namespace<L1>;
  namespace Run {
    type Context = $.ContextForFile<L1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/" | "/item/new" | "/item/$id" | "/docs/intro" | "/docs/$$rest"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/+page.marko")>;
declare module "../src/routes/+page.marko" {
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P2 = $.Template<"P2", typeof import("../src/routes/item/new/+page.marko")>;
declare module "../src/routes/item/new/+page.marko" {
  const Run: $.Namespace<P2>;
  namespace Run {
    type Context = $.ContextForFile<P2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/item/new"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P3 = $.Template<"P3", typeof import("../src/routes/item/$id/+page.marko")>;
declare module "../src/routes/item/$id/+page.marko" {
  const Run: $.Namespace<P3>;
  namespace Run {
    type Context = $.ContextForFile<P3> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/item/$id"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P4 = $.Template<"P4", typeof import("../src/routes/docs/intro/+page.marko")>;
declare module "../src/routes/docs/intro/+page.marko" {
  const Run: $.Namespace<P4>;
  namespace Run {
    type Context = $.ContextForFile<P4> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/docs/intro"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

type P5 = $.Template<"P5", typeof import("../src/routes/docs/$$rest/+page.marko")>;
declare module "../src/routes/docs/$$rest/+page.marko" {
  const Run: $.Namespace<P5>;
  namespace Run {
    type Context = $.ContextForFile<P5> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = $.Routes["/docs/$$rest"];
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}

declare module "../src/routes/+404.marko" {
  const Run: $.Namespace<any>;
  namespace Run {
    type Context = $.ContextForFile<any> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    export type Route = globalThis.MarkoRun.Route;
    export type Context = Run.Context;
    export type Handler = $.HandlerLike<Route>;
    export type GET = $.HandlerLike<Route, "GET">;
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    export type POST = $.HandlerLike<Route, "POST">;
    export type PUT = $.HandlerLike<Route, "PUT">;
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
  }
}
