/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
		"/": [L1, P1];
		"/foo/$id": [L1, P2];
	}> {}
}

type L1 = $.Template<"L1", typeof import("../src/routes/+layout.marko")>;
declare module "../src/routes/+layout.marko" {
  interface Input extends $.LayoutInput<L1> {}
  const Run: $.Namespace<L1>;
  namespace Run {
    type Context = $.ContextForFile<L1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/" | "/foo/$id"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P1 = $.Template<"P1", typeof import("../src/routes/+page.marko")>;
declare module "../src/routes/+page.marko" {
  const Run: $.Namespace<P1>;
  namespace Run {
    type Context = $.ContextForFile<P1> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}

type P2 = $.Template<"P2", typeof import("../src/routes/foo/$id/+page.marko")>;
declare module "../src/routes/foo/$id/+page.marko" {
  const Run: $.Namespace<P2>;
  namespace Run {
    type Context = $.ContextForFile<P2> & Marko.Global;
  }

  /** @deprecated use `Run` namespace instead */
  namespace MarkoRun {
    export { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform };
    /** @deprecated use the `Run` namespace instead */
    export type Route = $.Routes["/foo/$id"];
    /** @deprecated use `Run.Context` instead */
    export type Context = Run.Context;
    /** @deprecated define handlers with `Run.GET(...)`, `Run.POST(...)`, etc. instead */
    export type Handler = $.HandlerLike<Route>;
    /** @deprecated define handlers with `Run.GET(...)` instead */
    export type GET = $.HandlerLike<Route, "GET">;
    /** @deprecated define handlers with `Run.HEAD(...)` instead */
    export type HEAD = $.HandlerLike<Route, "HEAD">;
    /** @deprecated define handlers with `Run.POST(...)` instead */
    export type POST = $.HandlerLike<Route, "POST">;
    /** @deprecated define handlers with `Run.PUT(...)` instead */
    export type PUT = $.HandlerLike<Route, "PUT">;
    /** @deprecated define handlers with `Run.DELETE(...)` instead */
    export type DELETE = $.HandlerLike<Route, "DELETE">;
    /** @deprecated define handlers with `Run.PATCH(...)` instead */
    export type PATCH = $.HandlerLike<Route, "PATCH">;
    /** @deprecated define handlers with `Run.OPTIONS(...)` instead */
    export type OPTIONS = $.HandlerLike<Route, "OPTIONS">;
    /** @deprecated define handlers with `Run.QUERY(...)` instead */
    export type QUERY = $.HandlerLike<Route, "QUERY">;
  }
}
