/*
  WARNING: This file is automatically generated and any changes made to it will be overwritten without warning.
  Do NOT manually edit this file or your changes will be lost.

  Before writing or changing route files, READ the cheat sheet shipped with
  @marko/run — require.resolve("@marko/run/cheatsheet.md"), typically
  node_modules/@marko/run/cheatsheet.md — for the routing, handler,
  middleware, and validation conventions this file's types describe.
*/

import { NotHandled, NotMatched, GetPaths, PostPaths, GetablePath, GetableHref, PostablePath, PostableHref, Platform } from "@marko/run/namespace";
import type * as $ from "@marko/run";


declare module "@marko/run" {
	interface App extends $.DefineRoutes<{
	}> {}
}
